service: sls-python-data
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

resources: # CloudFormation template syntax from here on.
      Resources:
        usersTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: usersTable
            AttributeDefinitions:
              - AttributeName: pk
                AttributeType: S
            KeySchema:
              - AttributeName: pk
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            
